### ISSUE TITLE
Is this depricated

### ISSUE THREAD

**Issue by bokja** [thekdub/IC2-Refined#1]
I would love to help out on this project if you are still working on it

**Comment by thekdub** [comment]
I haven't had much time to work on this in the past few months. It's still a project I'm working on, however some of the issues (such as IC2's cable system) are going to take much more work than I had anticipated.

I honestly don't remember what I left off on with the repository. I did a bit of work that never got pushed since it was more of playing with ideas that didn't end up working out.

By all means, go ahead and help out if you're interested. I can't guarantee I'll have much activity on this project for the next few months though.

**Comment by ErkSterk** [comment]
Stumbled upon this repository a couple of days ago. This is exactly what i needed to start of recoding the energynet. I started remaking the EnergyNet and i am getting great tps results. It is still hella bugged and is more of a PoC at the moment, but I think this might work out! (Also code is rather dirty and is in need of heavy cleaning)
![2020-02-16_00 29 53](https://user-images.githubusercontent.com/25126670/74596728-8a3d4400-5053-11ea-8867-97bf40490853.png)

**Comment by ErkSterk** [comment]
Update, i just loaded over 24k high voltage solar panels, all with looping cables stacked under them x4 into a mass fab. server got stable 20tps! Currently only mfsus, massfabs, hvs and some machines are tested, some of them is acting strange with power consumption. Also some weird stuff with cables i havent yet sorted out.
